### ISSUE TITLE
Support for puppetserver (jruby)

### ISSUE THREAD

**Issue by andrekeller** [sihil/hiera-eyaml-gpg#23] opened 2015-01-18 10:26 UTC
Hi

currently hiera-eyaml-gpg fails to install with puppetserver, probably because the gpgme extension is not available/compatible with JRuby.

Any plans on adding support?

Regards

**Comment by raphink** [comment] 2015-02-14 00:17
The problem is that gpgme needs to be compiled because it's a native extension. [The puppetserver doc](https://github.com/puppetlabs/puppet-server/blob/master/documentation/gems.markdown#gems-with-native-c-extensions) is clear that this is not possible, and that we should try to use only pure Ruby libraries.

For that reason, I [forked the plugin yesterday](https://github.com/raphink/hiera-eyaml-gpg_ruby) (since I had to rewrite most of the code and needed to publish to rubygems for testing purposes) to port it to [ruby_gpg](https://github.com/raphink/ruby_gpg), a simple Ruby wrapper around the GPG binary.

@sihil Which of the following possibilities would be the best approach for you?

1) I keep my fork, which has most of the code rewritten (and some functionalities lost) in order to port it to `ruby_gpg`
2) You'd be interested in having some kind of fallback mechanism, so that if `gpgme` is not present/usable, it can fallback to using `ruby_gpg` instead
3) You'd want to get rid of `gpgme` eventually so your plugin works with puppetserver out of the box.

**Comment by sihil** [comment] 2015-02-14 12:25
Hi @raphink,

Glad to hear someone is working on this. I did look briefly at this and figured it was a pretty big piece of work (my intention had been to use a Java implementation of GPG when running in JRuby). Switching to ruby_gpg seems like a reasonable alternative.

I'd like to know more about the functionality you've had to strip out. Are they functions that will be possible to rewrite or are they impossible to do in ruby_gpg? Ultimately we only really need to get the parts that puppetserver uses to work in JRuby, the editing functionality in eyaml can continue to use gpgme.

I'm definitely interested in fixing this plugin so that it works for users out of the box regardless of their setup.

Thanks again for spending time on this.

**Comment by raphink** [comment] 2015-02-14 21:18
So would you like a PR for option 2 then?

My fork already implements both encryption and decryption, working fine with JRuby (although we only really care for decryption for the puppetserver). My code is much simpler than the `gpgmg` implementation. All errors are left to the command line pretty much (there isn't much choice) and I don't check keys at all (which is fine for decryption, as the command line will just fail if it doesn't find a key to decrypt the string). I haven't implemented the `gnupghome` option, but this will be rather trivial.

The `decrypt` code is at https://github.com/raphink/hiera-eyaml-gpg_ruby/blob/master/lib/hiera/backend/eyaml/encryptors/gpg.rb#L111. Note that I had to fork `ruby_gpg` too, in order to fix [a bug with JRuby](https://github.com/blaix/ruby_gpg/pull/2) and [allow multiple recipients when encrypting](https://github.com/blaix/ruby_gpg/pull/1). Hopefully, these will be merged soon (the upstream repo hasn't been touched in nearly 5 years, but the author is active on GitHub).

One option would be to make both `gpgme` and `ruby_gpg` optinal requirements for `hiera-eyaml-gpg`, and then do some kind of:

```ruby
begin
  require 'gpgme'
  impl = :gpgme
rescue
  require 'ruby_gpg'
  impl = :ruby_gpg
end
```

and then adapt the code to the loaded lib. What do you think?

**Comment by raphink** [comment] 2015-02-27 15:13
My changes to ruby_gpg were merged and released, so this PR doesn't depend
on my fork anymore.

**Closed** 2015-03-21 18:56 UTC
